services:
  ibeam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ibeam2
    env_file:
      - .env
    ports:
      - 127.0.0.1:500:5000
      - 127.0.0.1:501:5001
    network_mode: host # Required due to clientportal.gw IP restrictions
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
